
# Set the base image to Ubuntu
FROM    fumblesandfriends/ghost

# File Author / Maintainer
MAINTAINER Jonathan Kolb

# Install Forever and other dependencies
RUN npm install -g forever

COPY ./ghost-start /ghost-start
